use_frameworks!
inhibit_all_warnings!

target 'iOS' do
  platform :ios, "6.0"
  xcodeproj 'Baymax'
  link_with 'Baymax iOS'
  pod 'AFNetworking', '~> 2.5'
  pod 'JSONModel'
end

target 'Mac' do
    platform :osx, "10.9"
    xcodeproj 'Baymax'
    link_with 'Baymax Mac'
    pod 'AFNetworking', '~> 2.5'
    pod 'JSONModel'
end